
# Services

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      args:
        CERT: ${CERT}
        KEY: ${KEY}
      context: ./requirements/nginx
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    env_file: .env
    restart: always
    networks:
      - inception
    volumes:
      - wordpress-db:/var/lib/mysql


  wordpress:
   container_name: wordpress
   build: ./requirements/wordpress
   env_file: .env
   image: wordpress
   depends_on:
     - mariadb
   volumes:
     - wordpress-files:/var/www/html


networks:
  inception:
    driver: bridge

volumes:
  wordpress-db:
  wordpress-files: