# Services
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      args:
        CERT: ${CERT}
        KEY: ${KEY}
      context: ./requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    env_file: .env
    restart: always
    networks:
      - inception
    volumes:
      - wordpress-db:/var/lib/mysql

  wordpress:
   container_name: wordpress
   build: ./requirements/wordpress
   env_file: .env
   image: wordpress
   depends_on:
     - mariadb
   volumes:
     - wordpress-files:/var/www/html
   restart: always
   networks:
     - inception

networks:
  inception:
    name: inception
    driver: bridge

volumes:
 wordpress-db:
   driver: local
   driver_opts:
     device: /Users/arobu/data/mariadb
     o: bind
     type: none
 wordpress-files:
   driver: local
   driver_opts:
     device: /Users/arobu/data/wordpress
     o: bind
     type: none
